version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: schoolsync_db
    environment:
      POSTGRES_USER: schoolsync
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: schoolsync_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: